### PR TITLE
Add support for [*] operator

### PR DESCRIPTION
**Pull request by jsstylos**
This addresses #32 and (partially) #21, adding support for the [*] operator. This doesn't need a direction arrow because only one side can be unconstrained, so we can infer which direction; if both sides are unconstrained then the graph is unsolvable regardless.

The inference algorithm used requires that at each stage there be at least one node with a single computed/unknown edge, but this can be anywhere in the graph. This enables support for inputs where the only constraint is in the middle of the graph, such as:

```
A [*] B
B [*] C
C [*] D
D [100] E
E [*] F
F [*] G
```

More useful input would be something like:

```
Work [2000] Paycheck
Paycheck [600] Taxes
Paycheck [*] Take-home
Take-home [800] Rent
Take-home [200] Food
Take-home [*] Savings
Rent [*] Spending
Food [*] Spending
```

image

The code could use some more testing and cleaning up, and has a known bug with generating console errors when given unsolvable input, but I'm putting the code up here for @nowthis and others to play around with.

Percentages would also be possible if this seems like a direction people are interested in.

### CODE REVIEW

**Comment by jsstylos** [comment]
I put up a (temporary) web version for people to play around with and give feedback: https://jsstylos-sankeymatic.mybluemix.net

**Comment by waldyrious** [comment]
Tested it with this script that demonstrates ranked voting:

```
' == ROUND 1 ==
' Candidates that move to the next round with all their votes:
Ana r1 [25] Ana r2
Ben r1 [20] Ben r2
Che r1 [16] Che r2
' Second choices for the least voted candidate:
Dan r1 [5] Ana r2
Dan r1 [4] Ben r2
Dan r1 [2] None r2
 
' == ROUND 2 ==
' Candidates that move to the next round with all their votes:
Ana r2 [*] Ana r3
Ben r2 [*] Ben r3
' Second choices for the least voted candidate:
Che r2 [3] Ana r3
Che r2 [11] Ben r3
Che r2 [*] None r3
```

([Here](https://pastebin.com/eyxzJ5sK)'s a version of the script with more detailed comments explaining the numbers.)

Works quite well! Here's the result:

sankeymatic_600x600

**Comment by jonz-secops** [comment]
was this ever integrated? asking since the web version and this repo are not in synch so hard to tell.

**Comment by nowthis** [comment]
I accepted PR #77 not long ago as an implementation of calculated flows to adopt and refine.

However, there are two key insights contained in this PR that I also want to adopt:

1. Resolve the least-unambiguous unknowns first, i.e. any flow where no other unknown values are affecting the parent node.
2. Unknown flows which 'terminate' (meaning: arrive at an endpoint or begin at an origin) should be resolved **after** other flows with the same number of unknowns, because the terminating node behaves a bit like an additional unknown.

Incorporating these two ideas will result in more consistent and more intuitive results from flow calculations, and the order of the input data will matter less than it does today.

I am currently working on a merge commit to add these improvements. I am attempting to manage it so that this PR appears accepted/merged and @jsstylos is properly credited.

**Comment by nowthis** [comment]
There will be a day when I get the procedure completely right for merging PRs, but Saturday was not that day.

As mentioned in the message for 180432ea0bd7922294e677f3bf321aac28802886, the commit which contains the adopted logic is **actually** https://github.com/nowthis/sankeymatic/commit/298d48006ec60e9abadb075256ef7096e57dc8a2. That's where to find the relevant diff, plus some extensive commentary & examples in the log.

Apologies for the wait, @jsstylos. You are now properly listed as a contributor.

**Pull request merged**
